### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by berendsliedrecht** [openwallet-foundation/bifold-wallet#20]
When trying to run the application on Android, I encountered two issues with the setup.

1: The README did not mention that I have to `pack` aries-framework-javascript myself.
2: That I have to create a .env file with the correct entries.

template env file, found on Rocketchat:

MEDIATOR_URL=https://dd652a260851.ngrok.io
GENESIS_URL=https://raw.githubusercontent.com/Indiciotech/indicionetwork/main/genesis_files/pool_transactions_testnet_genesis

cheers!

**Comment by JamesKEbert** [comment]
Thank you @blu3beri! We haven't quite gotten to fully including all of the documentation we'd like the project to have. For 1., @DavidClawson and I have just merged in a PR #21 which does add the aries-framework-javascript.tgz so that you don't have to, which is quite nice IMO.
And I will be adding that template env file to the documentation along with documentation for iOS here as soon as I can!

**Comment by JamesKEbert** [comment]
README has been updated with additional setup information, including the env file info.
