### ISSUE TITLE
Credential Issuance not working with AIP 2.0

### ISSUE THREAD

**Issue by HiraSiddiqui** [openwallet-foundation/bifold-wallet#680]
Hi,

I have been running aries mobile agent with aries aca-py cloud agent by running faber agent from here:
https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#the-alicefaber-python-demo

If I run the faber cloud agent with AIP 1.0 (using flag --aip 10), then the credential issuance works perfectly. But if I run the faber cloud agent with AIP 2.0, then it prints the following error message:

"Value did:peer:xyz is not a valid indy decentralized identifier (DID)"

![image](https://user-images.githubusercontent.com/18054461/227951492-852299ed-9b97-41c9-8d86-f72ba84378ed.png)

My question is, is Aries Mobile Agent not compatible with AIP 2.0?

**Comment by bryce-mcmath** [comment]
Will investigate

**Comment by wadeking98** [comment]
I believe this is because the QR code doesn't render properly in docker playground. It seems like some characters are not supported so they show up as tofu which causes the QR code to be corrupted:
![image.png](https://images.zenhubusercontent.com/5fc52e1a365e55a8d5b3f428/1b454468-a4b4-4ece-8cc3-6f951355b281)
For whatever reason, if you use AIP 1.0 the QR code doesn't contain any of these invalid character so the QR code is not malformed:
![image.png](https://images.zenhubusercontent.com/5fc52e1a365e55a8d5b3f428/d4fdae33-84be-4947-b5a1-2ccc6547ac3b)

**Comment by wadeking98** [comment]
scratch that I'm running into the same issue when I run it from docker locally. I think this might be an issue with the demo though because the BC Wallet Showcase uses Traction which uses AIP 2.0
