### ISSUE TITLE
Duplicate scan of QR code, odd behaviour

### ISSUE THREAD

**Issue by andrewwhitehead** [openwallet-foundation/bifold-wallet#694]
When a QR code for an out-of-band invitation is scanned, having already been scanned before, the message "Invalid QR code. Please try again." is displayed. Presumably this is because there is already a record associated with that connection. It seems that the app goes on to try to resolve the invitation as a URL (performing a GET request), although it has already identified the `oob` component.

Tested on iOS.

**Comment by bryce-mcmath** [comment]
Need to confirm it's caused by duplicate connection, verification required, may need UX

**Comment by cvarjao** [comment]
Need more investigation. Is there a place to test? we may need to escalate this to AFJ.

**Comment by bryce-mcmath** [comment]
I found a way to clear out old connection invitations so that we can reuse them, but it depends on being able to tell if a connection invitation is made to be multi use. The way to tell is if `oobRecord.reusable` is set to `true` but right now, testing with Traction, it's always false - even for multi use connections. Investigating to see if it's an issue in Traction or possibly ACA-Py.
