### ISSUE TITLE
The unlock button shuld not be active unless all 6 PIN digits are entered

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#925]
### Description of problem

You can press the "unlock" button on the pin PIN screen with any number of digits.

### Expected behavior

 Since 6 are required, it should wait for all 6 to be input before becoming active.

### Steps to reproduce

At the "Enter PIN" screen, press the unlock button.

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by knguyenBC** [comment]
I think it's fine the way it is. Its a little extra security. If someone knew the passcode, they'd know its a 6 digit number. If they didn't know, then they'd try any number of digits. We'd want to count each attempt to ensure its locked if too many attempts were made. 

Also. trying to avoid disabled buttons because as a principle, people need to know why they can't press a button and a disabled state of a button doesn't inform people on why they can't click on it.

**Comment by wadeking98** [comment]
resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/1017

**Comment by nodlesh** [comment]
This can be closed. Tested in 1279. I don't have access to close in this repo.
